/* Base Set Custom Data - Prices & Rarities */
window.BASE_SET_DB = {
    "1": { n: "Alakazam", p: 35, r: "rare" },
    "2": { n: "Blastoise", p: 90, r: "epic" },
    "3": { n: "Chansey", p: 30, r: "rare" },
    "4": { n: "Charizard", p: 280, r: "legendary" },
    "5": { n: "Clefairy", p: 12, r: "uncommon" },
    "6": { n: "Gyarados", p: 14, r: "uncommon" },
    "7": { n: "Hitmonchan", p: 13, r: "uncommon" },
    "8": { n: "Machamp", p: 12, r: "uncommon" },
    "9": { n: "Magneton", p: 11, r: "uncommon" },
    "10": { n: "Mewtwo", p: 35, r: "rare" },
    "11": { n: "Nidoking", p: 14, r: "uncommon" },
    "12": { n: "Ninetales", p: 10, r: "uncommon" },
    "13": { n: "Poliwrath", p: 12, r: "uncommon" },
    "14": { n: "Raichu", p: 22, r: "uncommon" },
    "15": { n: "Venusaur", p: 60, r: "rare" },
    "16": { n: "Zapdos", p: 18, r: "uncommon" },
    "17": { n: "Beedrill", p: 6, r: "common" },
    "18": { n: "Dragonair", p: 12, r: "uncommon" },
    "19": { n: "Dugtrio", p: 5, r: "common" },
    "20": { n: "Electabuzz", p: 6, r: "common" },
    "21": { n: "Electrode", p: 5, r: "common" },
    "22": { n: "Pidgeotto", p: 5, r: "common" },
    "23": { n: "Arcanine", p: 12, r: "uncommon" },
    "24": { n: "Charmeleon", p: 2.5, r: "common" },
    "25": { n: "Dewgong", p: 4, r: "common" },
    "26": { n: "Dratini", p: 5, r: "common" },
    "27": { n: "Farfetch'd", p: 4, r: "common" },
    "28": { n: "Growlithe", p: 2.5, r: "common" },
    "29": { n: "Haunter", p: 5, r: "common" },
    "30": { n: "Ivysaur", p: 6, r: "common" },
    "31": { n: "Jynx", p: 4, r: "common" },
    "32": { n: "Kadabra", p: 5, r: "common" },
    "33": { n: "Kakuna", p: 2.5, r: "common" },
    "34": { n: "Machoke", p: 5, r: "common" },
    "35": { n: "Magikarp", p: 3, r: "common" },
    "36": { n: "Magmar", p: 5, r: "common" },
    "37": { n: "Nidorino", p: 4, r: "common" },
    "38": { n: "Poliwhirl", p: 5, r: "common" },
    "39": { n: "Porygon", p: 5, r: "common" },
    "40": { n: "Raticate", p: 4, r: "common" },
    "41": { n: "Seel", p: 2.5, r: "common" },
    "42": { n: "Wartortle", p: 6, r: "common" },
    "43": { n: "Abra", p: 2, r: "basic" },
    "44": { n: "Bulbasaur", p: 2.5, r: "common" },
    "45": { n: "Caterpie", p: 0.7, r: "basic" },
    "46": { n: "Charmander", p: 2.5, r: "common" },
    "47": { n: "Diglett", p: 0.7, r: "basic" },
    "48": { n: "Doduo", p: 0.7, r: "basic" },
    "49": { n: "Drowzee", p: 0.7, r: "basic" },
    "50": { n: "Gastly", p: 0.8, r: "basic" },
    "51": { n: "Koffing", p: 0.7, r: "basic" },
    "52": { n: "Machop", p: 0.7, r: "basic" },
    "53": { n: "Magnemite", p: 0.8, r: "basic" },
    "54": { n: "Metapod", p: 0.9, r: "basic" },
    "55": { n: "Nidoran♂", p: 0.7, r: "basic" },
    "56": { n: "Onix", p: 2, r: "basic" },
    "57": { n: "Pidgey", p: 0.6, r: "basic" },
    "58": { n: "Pikachu", p: 3, r: "common" },
    "59": { n: "Poliwag", p: 0.7, r: "basic" },
    "60": { n: "Ponyta", p: 0.7, r: "basic" },
    "61": { n: "Rattata", p: 0.6, r: "basic" },
    "62": { n: "Sandshrew", p: 0.7, r: "basic" },
    "63": { n: "Squirtle", p: 3, r: "common" },
    "64": { n: "Starmie", p: 2.5, r: "common" },
    "65": { n: "Staryu", p: 0.8, r: "basic" },
    "66": { n: "Tangela", p: 2, r: "basic" },
    "67": { n: "Voltorb", p: 0.7, r: "basic" },
    "68": { n: "Vulpix", p: 0.8, r: "basic" },
    "69": { n: "Weedle", p: 0.6, r: "basic" },
    "70": { n: "Clefairy Doll", p: 6, r: "common" },
    "71": { n: "Computer Search", p: 35, r: "rare" },
    "72": { n: "Devolution Spray", p: 4, r: "common" },
    "73": { n: "Imposter Professor Oak", p: 2.5, r: "common" },
    "74": { n: "Item Finder", p: 12, r: "uncommon" },
    "75": { n: "Lass", p: 5, r: "common" },
    "76": { n: "Pokémon Breeder", p: 5, r: "common" },
    "77": { n: "Pokémon Trader", p: 4, r: "common" },
    "78": { n: "Scoop Up", p: 12, r: "uncommon" },
    "79": { n: "Super Energy Removal", p: 10, r: "uncommon" },
    "80": { n: "Defender", p: 0.7, r: "basic" },
    "81": { n: "Energy Retrieval", p: 2.5, r: "common" },
    "82": { n: "Full Heal", p: 0.6, r: "basic" },
    "83": { n: "Maintenance", p: 2.5, r: "common" },
    "84": { n: "PlusPower", p: 4, r: "common" },
    "85": { n: "Pokémon Center", p: 2.5, r: "common" },
    "86": { n: "Pokémon Flute", p: 4, r: "common" },
    "87": { n: "Pokédex", p: 0.8, r: "basic" },
    "88": { n: "Professor Oak", p: 4, r: "common" },
    "89": { n: "Revive", p: 0.7, r: "basic" },
    "90": { n: "Super Potion", p: 0.7, r: "basic" },
    "91": { n: "Bill", p: 2.5, r: "common" },
    "92": { n: "Energy Removal", p: 4, r: "common" },
    "93": { n: "Gust of Wind", p: 4, r: "common" },
    "94": { n: "Potion", p: 0.6, r: "basic" },
    "95": { n: "Switch", p: 0.7, r: "basic" },
    "96": { n: "Double Colorless Energy", p: 12, r: "uncommon" },
    "97": { n: "Fighting Energy", p: 0.5, r: "basic" },
    "98": { n: "Fire Energy", p: 0.5, r: "basic" },
    "99": { n: "Grass Energy", p: 0.5, r: "basic" },
    "100": { n: "Lightning Energy", p: 0.5, r: "basic" },
    "101": { n: "Psychic Energy", p: 0.5, r: "basic" },
    "102": { n: "Water Energy", p: 0.5, r: "basic" }
};
